#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: furushchev <furushchev@jsk.imi.i.u-tokyo.ac.jp>

import os
import sys
from respeaker_ros.respeaker2 import PARAMETERS_array2, init_respeaker


def main(out):
    dev = init_respeaker()
    if not dev:
        print('No device found. Please connect a device.')
        return
    with open(out, "w") as f:
        f.write("""\
#!/usr/bin/env python
#
# WARNING!!
# This file is automatically generated.
# DO NOT MODIFY THIS FILE!
#
# To generate this file, please run:
# cd /path/to/this/package
# python ./scripts/respeaker_gencfg.py
#

from dynamic_reconfigure.parameter_generator_catkin import *

gen = ParameterGenerator()

#       name    type     level     description     default      min      max""")

        for key, val in PARAMETERS_array2.items():
            type_, max, min, rw_ = val[2:6]
            desc = " ".join(val[6:])
            default = dev.read(key)
            if rw_ != "rw":
                continue
            if type_ == "int" and max == 1 and min == 0:
                if def_ == 1:
                    def_ = True
                else:
                    def_ = False
                f.write(f"""
gen.add("{key}", bool_t, 0, "{desc}", {default})""")
            elif type_ == "int":
                f.write(f"""
gen.add("{key}", int_t, 0, "{desc}", {default}, {min}, {max})""")
            elif type_ == "float":
                f.write(f"""
gen.add("{key}", double_t, 0, "{desc}", {default:f}, {min:f}, {max:f})""")
            else:
                print(f"Param '{key}' is ignored.")
        f.write("""

exit(gen.generate("respaker_ros", "respeaker_ros", "RespeakerArray2"))
""")

    os.chmod(out, 0o775)

    print("Saved cfg to %s" % out)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        outpath = sys.argv[1]
    else:
        outpath = os.path.join(
            os.path.abspath(os.path.dirname(__file__)),
            "..", "cfg", "RespeakerArray2.cfg")
    main(outpath)
