#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: furushchev <furushchev@jsk.imi.i.u-tokyo.ac.jp>

import os
import sys
from respeaker_ros.respeaker3800 import PARAMETERS_3800, Respeaker3800, EXTRA_PARAMETER3800


def writeparam(file, key, type_, desc, def_, min, max):
    if type_ in ["uint8", "uint16", "uint32", "int8", "int16", "int32"] and max == 1 and min == 0:
        if def_ == 1:
            def_ = True
        else:
            def_ = False
        file.write(f"""
gen.add("{key}", bool_t, 0, "{desc}", {def_})""")
    elif type_ in ["uint8", "uint16", "uint32", "int8", "int16", "int32"]:
        file.write(f"""
gen.add("{key}", int_t, 0, "{desc}", {def_}, {min}, {max})""")
    elif type_ == "float":
        file.write(f"""
gen.add("{key}", double_t, 0, "{desc}", {def_:f}, {min:f}, {max:f})""")
    else:
        print(f"Param '{key}' is ignored.")

def main(out):
    dev = Respeaker3800()
    if not dev:
        print('No device found. Please connect a device.')
        return
    with open(out, "w") as f:
        f.write("""\
#!/usr/bin/env python
#
# WARNING!!
# This file is automatically generated.
# DO NOT MODIFY THIS FILE!
#
# To generate this file, please run:
# cd /path/to/this/package
# python ./scripts/respeaker_gencfg.py
#

from dynamic_reconfigure.parameter_generator_catkin import *

gen = ParameterGenerator()

#       name    type     level     description     default      min      max""")

        for key, val in PARAMETERS_3800.items():
            #print(key)
            count, rw_, type_, desc = val[2:6]
            default = dev.read(key)
            if rw_ != "rw":
                # only configure RW parameters
                continue
            if count != 1:
                print(f"ignore param {key}: count!=1")
                # only configure single value parameters
                continue

            # manually added
            def_ = default[0]
            try:
                min, max = val[6:8]
            except:
                print(f"missing min/max values for {key}({type_})")
                continue
            print(f"KEY: {key}, default:{default}")
            writeparam(f, key, type_, desc, def_, min, max)

        for key, val in EXTRA_PARAMETER3800.items():
            type_, desc, default, min, max = val
            writeparam(f, key, type_, desc, default, min, max)

        f.write("""

exit(gen.generate("respaker_ros", "respeaker_ros", "Respeaker3800"))
""")

    os.chmod(out, 0o775)

    print("Saved cfg to %s" % out)


if __name__ == '__main__':
    if len(sys.argv) > 1:
        outpath = sys.argv[1]
    else:
        outpath = os.path.join(
            os.path.abspath(os.path.dirname(__file__)),
            "..", "cfg", "Respeaker3800.cfg")
    main(outpath)
