models:
  de:
    voice: "de_DE-karlsson-low"
  en: 
    voice: "en_GB-alan-medium"
  es:
    voice: "es_MX-ald-medium"
  zh:
    voice: zh_CN-huayan-medium
  
  thorsten:
    voice: "de_DE-thorsten-low"
  alan:
    voice: "en_GB-alan-medium"
  kerstin:
    voice: de_DE-kerstin-low
  ramona:
    voice: de_DE-ramona-low
  ryan:
    voice: en_US-ryan-low
